#pragma once

/// Represents the swinging arm
class Quad {

public:
  // By default, everything is initialized to zero
protected:
  // Position and Orientation ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  // Position along z axis
  float z = 0;

  // Position along x axis
  float x = 0;

  // Variables for dynamics function ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  /// Thrust generated by the motor propellor pair
  float thrust = 0;

public:
  /// Dynamics of the 2D quadcopter
  void Dynamics(const float commanded_thrust, const float commanded_torque);
};