# General Rigid Body Parameters:

# Mass of the quadcopter
mass: 0.7 #[kg]

# Geometrical properties
arm_length: 0.171
inertia_2d: 0.0034

# Motor time constant
motor_time_constant: 0.05

# Air drag coefficient
drag_coeff: 1.2

# Maximum thrust can be produced by the motors
motor_thrust_max: 6.25

# Maximum thrust can be produced by the motors
motor_thrust_min: 1.75

# Maximum roll angle
roll_max: 0.5
# Relation btw square of motor speed and motor thrust
# kf: 6.11e+06
